# Generated by Django 4.2.6 on 2023-10-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventDatetime',
            new_name='EventDateTime',
        ),
    ]
