# Generated by Django 4.2.6 on 2023-10-13 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_events_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteText', models.CharField(max_length=100)),
                ('authorID', models.CharField(max_length=100)),
                ('anonymous', models.BooleanField()),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickyNotes', to='events.event')),
            ],
        ),
    ]
