# Generated by Django 4.2.6 on 2023-10-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_eventdatetime_event_eventdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
