# Generated by Django 4.2.6 on 2023-10-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_eventdatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='EventDateTime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='closeDate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='openDate',
        ),
    ]
