# Generated by Django 4.2.3 on 2023-10-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_finishdate_remove_event_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='finish_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finish Date & Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date & Time'),
        ),
    ]
