# Generated by Django 4.2.6 on 2023-10-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_attendee',
            field=models.BooleanField(default=True),
        ),
    ]
