# Generated by Django 4.2.6 on 2023-10-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_organiser_pending',
            field=models.BooleanField(default=False),
        ),
    ]
