# Generated by Django 4.2.6 on 2023-10-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_organiser',
            field=models.BooleanField(default=False),
        ),
    ]
