# Generated by Django 4.2.6 on 2023-10-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_organiser_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_organiser_pending',
        ),
    ]
